# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zTibtY4YpKzWzY3h34O3-lNz_-7VCIQx
"""

import sys
!{sys.executable} -m pip install streamlit
import streamlit as st
import pandas as pd
import numpy as np
import joblib
import gdown
import os

# -------------------------------
# Load Model from Google Drive
# -------------------------------
@st.cache_resource
def load_model():
    model_path = "final_model.pkl"

    if not os.path.exists(model_path):
        url = "https://drive.google.com/uc?id=1JjtTF5knBivXmNyC2VQoJWyL57gY0JaF"
        gdown.download(url, model_path, quiet=False)

    return joblib.load(model_path)

model = load_model()

# -------------------------------
# Page Config
# -------------------------------
st.set_page_config(page_title="Forest Cover Prediction", layout="wide")

st.title("🌲 Forest Cover Type Prediction App")
st.write("Predict forest cover type using environmental features")

# -------------------------------
# Sidebar Inputs
# -------------------------------
st.sidebar.header("Input Features")

def user_input_features():

    Elevation = st.sidebar.number_input("Elevation", 1000, 4000, 2500)
    Aspect = st.sidebar.slider("Aspect", 0, 360, 100)
    Slope = st.sidebar.slider("Slope", 0, 60, 10)

    Horizontal_Distance_To_Hydrology = st.sidebar.number_input(
        "Horizontal Distance To Hydrology", 0, 1000, 200
    )
    Vertical_Distance_To_Hydrology = st.sidebar.number_input(
        "Vertical Distance To Hydrology", -100, 500, 50
    )

    Horizontal_Distance_To_Roadways = st.sidebar.number_input(
        "Distance To Roadways", 0, 5000, 1000
    )

    Hillshade_9am = st.sidebar.slider("Hillshade 9am", 0, 255, 200)
    Hillshade_Noon = st.sidebar.slider("Hillshade Noon", 0, 255, 220)
    Hillshade_3pm = st.sidebar.slider("Hillshade 3pm", 0, 255, 180)

    Horizontal_Distance_To_Fire_Points = st.sidebar.number_input(
        "Distance To Fire Points", 0, 5000, 1500
    )

    # Wilderness Area
    wilderness = st.sidebar.selectbox("Wilderness Area", ["1", "2", "3", "4"])

    Wilderness_Area1 = 1 if wilderness == "1" else 0
    Wilderness_Area2 = 1 if wilderness == "2" else 0
    Wilderness_Area3 = 1 if wilderness == "3" else 0
    Wilderness_Area4 = 1 if wilderness == "4" else 0

    # Soil Type
    soil = st.sidebar.selectbox("Soil Type", [str(i) for i in range(1, 41)])

    soil_features = {f"Soil_Type{i}": 0 for i in range(1, 41)}
    soil_features[f"Soil_Type{soil}"] = 1

    data = {
        "Elevation": Elevation,
        "Aspect": Aspect,
        "Slope": Slope,
        "Horizontal_Distance_To_Hydrology": Horizontal_Distance_To_Hydrology,
        "Vertical_Distance_To_Hydrology": Vertical_Distance_To_Hydrology,
        "Horizontal_Distance_To_Roadways": Horizontal_Distance_To_Roadways,
        "Hillshade_9am": Hillshade_9am,
        "Hillshade_Noon": Hillshade_Noon,
        "Hillshade_3pm": Hillshade_3pm,
        "Horizontal_Distance_To_Fire_Points": Horizontal_Distance_To_Fire_Points,
        "Wilderness_Area1": Wilderness_Area1,
        "Wilderness_Area2": Wilderness_Area2,
        "Wilderness_Area3": Wilderness_Area3,
        "Wilderness_Area4": Wilderness_Area4,
    }

    data.update(soil_features)

    return pd.DataFrame([data])


input_df = user_input_features()

# -------------------------------
# Show Input
# -------------------------------
st.subheader("Input Data")
st.write(input_df)

# -------------------------------
# Prediction
# -------------------------------
if st.button("Predict"):

    try:
        # Ensure correct column order
        if hasattr(model, "feature_names_in_"):
            input_df = input_df[model.feature_names_in_]

        prediction = model.predict(input_df)[0]

        st.subheader("Prediction Result")

        cover_dict = {
            1: "Spruce/Fir",
            2: "Lodgepole Pine",
            3: "Ponderosa Pine",
            4: "Cottonwood/Willow",
            5: "Aspen",
            6: "Douglas-fir",
            7: "Krummholz"
        }

        result = cover_dict.get(prediction, "Unknown")

        st.success(f"🌳 Predicted Cover Type: {result}")

        # Probability (if available)
        if hasattr(model, "predict_proba"):
            prob = model.predict_proba(input_df)
            st.subheader("Prediction Probability")
            st.write(prob)

    except Exception as e:
        st.error(f"Error: {e}")