# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17KWQIylufM1eYK7Ap8_ghUzVLMFNSBPj
"""

import streamlit as st
import numpy as np
import joblib

# ======================
# PAGE CONFIG
# ======================
st.set_page_config(page_title="Forest Cover Predictor", layout="centered")

# ======================
# LOAD MODEL
# ======================
model = joblib.load("model.pkl")

# ======================
# TITLE
# ======================
st.title("🌲 Forest Cover Type Prediction")
st.markdown("Predict forest cover type based on environmental features")

# ======================
# INPUT SECTION
# ======================
st.subheader("Enter Feature Values")

col1, col2 = st.columns(2)

with col1:
    Elevation = st.number_input("Elevation", 0, 5000)
    Aspect = st.number_input("Aspect", 0, 360)
    Slope = st.number_input("Slope", 0, 90)
    Horizontal_Distance_To_Hydrology = st.number_input("Hydrology Distance", 0, 1000)
    Vertical_Distance_To_Hydrology = st.number_input("Vertical Hydrology Distance", -500, 500)

with col2:
    Horizontal_Distance_To_Roadways = st.number_input("Roadway Distance", 0, 5000)
    Hillshade_9am = st.number_input("Hillshade 9am", 0, 255)
    Hillshade_Noon = st.number_input("Hillshade Noon", 0, 255)
    Hillshade_3pm = st.number_input("Hillshade 3pm", 0, 255)
    Horizontal_Distance_To_Fire_Points = st.number_input("Fire Points Distance", 0, 5000)

# ======================
# PREDICTION
# ======================
if st.button("Predict Cover Type"):

    features = np.array([[
        Elevation, Aspect, Slope,
        Horizontal_Distance_To_Hydrology,
        Vertical_Distance_To_Hydrology,
        Horizontal_Distance_To_Roadways,
        Hillshade_9am, Hillshade_Noon, Hillshade_3pm,
        Horizontal_Distance_To_Fire_Points
    ]])

    prediction = model.predict(features)

    st.success(f"🌳 Predicted Cover Type: {prediction[0]}")